hotfix: pip install in action

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -33,9 +33,10 @@ jobs:
           username: "ubuntu"
           script: |
             cd /home/ubuntu/fiis-buscador/
-            export PATH=$PATH:/usr/local/bin
-            which python || sudo apt update && sudo apt install -y python
-            which pip || sudo apt install -y python-pip
+            source ~/.bashrc || true
+            export PATH=$PATH:/home/ubuntu/.local/bin:/usr/local/bin:/usr/bin
+            which python || echo "Python not found"
+            which pip || echo "Pip not found"
             pip install -r requirements.txt
             pkill -f streamlit || true
             nohup streamlit run main.py > logs/streamlit.log 2>&1 &
